name: Build and Push FragmentServer Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: GitHub Container Registry Login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      
      - name: Username to Lowercase
        run: echo "REPO_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build FragmentServer Image
        run: |
          docker build -t ghcr.io/${{ env.REPO_OWNER }}/fragmentserver:latest -f ./src/api/Dockerfile ./src/api

      - name: Push FragmentServer Image
        run: docker push ghcr.io/${{ env.REPO_OWNER }}/fragmentserver:latest