name: Build and Push FragmentServer Image

on:
  workflow_run:
    workflows: ["Testing API"]
    types:
      - completed

jobs:
    build-and-push:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
          - name: Code Checkout
            uses: actions/checkout@v3

          - name: GitHub Container Registry Login
            run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        
          - name: Username to Lowercase
            run: echo "REPO_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

          - name: Set commit tag
            id: get_tag
            run: |
              if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
                tag="${GITHUB_REF#refs/tags/}"
              else
                tag="latest"
              fi
              echo "commit_tag=$tag" >> $GITHUB_ENV
          
          - name: Debug commit tag
            run: | 
                echo "Commit tag is: ${{ env.commit_tag }}"

          - name: Build FragmentServer Image
            run: |
                docker build -t ghcr.io/${{ env.REPO_OWNER }}/fragmentserver:${{ env.IMAGE_TAG }} -f ./src/api/Dockerfile ./src/api

          - name: Push FragmentServer Image
            run: docker push ghcr.io/${{ env.REPO_OWNER }}/fragmentserver:${{ env.IMAGE_TAG }}