name: Testing API

on:
    push:
        branches:
            - main
            - dev

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            
            #- name: Update package list
            #  run: sudo apt-get update
        
            - name: Prepare for key generation
              run: |
                chmod +x scripts/*
                bash scripts/prep.sh
        
            - name: Test key generation
              run: bash scripts/testing_prep.sh ${{ secrets.SUPABASE_JWT_SECRET }} ${{ secrets.SUPABASE_URL }} ${{ secrets.SUPABASE_KEY }} .

            - name: Build and run containers
              run: docker compose -f docker-compose.test.yml up -d

            - name: Initialize database
              run: bash scripts/wait_and_initialize_db.sh
        
            - name: Run tests
              run: docker exec $(docker ps -qf "name=gateway") pytest
        
            - name: Stop containers
              run: docker compose -f docker-compose.test.yml down
              
            - name: Set commit tag
              id: get_tag
              run: |
                if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
                  tag="${GITHUB_REF#refs/tags/}"
                else
                  tag="latest"
                fi
                echo "commit_tag=$tag" >> $GITHUB_ENV