name: Testing API

on:
    pull_request:
        branches:
            - main
            - dev
    push:
        branches:
            - main
            - dev

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            
            #- name: Update package list
            #  run: sudo apt-get update
        
            - name: Prepare for key generation
              run: |
                chmod +x scripts/*
                bash scripts/prep.sh
        
            - name: Test key generation
              run: bash scripts/testing_prep.sh ${{ secrets.SUPABASE_JWT_SECRET }} ${{ secrets.SUPABASE_URL }} ${{ secrets.SUPABASE_KEY }} .

            - name: Build and run containers
              run: docker compose -f docker-compose.test.yml up -d

            - name: Initialize database
              run: bash scripts/wait_and_initialize_db.sh
        
            - name: Run tests
              run: docker exec $(docker ps -qf "name=gateway") pytest
        
            - name: Stop containers
              run: docker compose -f docker-compose.test.yml down